Events/AdminPage/urls.py
from django.urls import path
from . import views

app_name = 'adminpage'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_event/', views.add_event, name='add_event'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('edit_event/<int:event_id>/', views.edit_event, name='edit_event'),
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
]

Events/Event/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'Event'

urlpatterns = [
    path('', views.login_view, name='landing'),
    path('list/', views.event_list, name='event_list'),
    path('join/<int:event_id>/', views.join_event, name='join_event'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.custom_logout_view, name='logout')
]

Events/Events/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminpage/', include(('AdminPage.urls', 'AdminPage'), namespace='AdminPage')),
    path('', include('Event.urls', namespace='Event')),
]

Events/Event/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    location = models.CharField(max_length=200)
    organizer = models.ForeignKey(User, related_name='organized_events', on_delete=models.CASCADE)
    participants = models.ManyToManyField(User, related_name='participating_events', blank=True)
    date_from = models.DateField(verbose_name='Start Date', default=timezone.now)
    date_to = models.DateField(verbose_name='End Date', default=timezone.now)

    def __str__(self):
        return self.title

Events/Event/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Event

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'

        for fieldname in ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']:
            self.fields[fieldname].label = ''
            self.fields[fieldname].help_text = ''

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'

        for fieldname in ['username', 'password']:
            self.fields[fieldname].label = ''
            self.fields[fieldname].help_text = ''

class EventForm(forms.ModelForm):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=True, label='From')
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=True, label='To')

    class Meta:
        model = Event
        fields = ['title', 'description', 'location', 'organizer']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Event Title'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description'}),
            'location': forms.TextInput(attrs={'placeholder': 'Location'}),
            'organizer': forms.Select(attrs={'placeholder': 'Organizer'}),
        }

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        
        self.fields['organizer'].queryset = User.objects.filter(is_superuser=True)

        for fieldname in ['title', 'description', 'location']:
            self.fields[fieldname].label = ''
            self.fields[fieldname].help_text = ''

Events/Event/views.py
from django.shortcuts import render
from .models import Event
from .forms import EventForm
from django.shortcuts import render, redirect
from .forms import SignUpForm, LoginForm
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

def landing_page(request):
    return render(request, 'events/landing.html')

def login_view(request):
    form = LoginForm(data=request.POST or None)
    if request.method == 'POST' and form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('Event:event_list')  
        else:
            form.add_error(None, 'Invalid username or password')

    return render(request, 'events/landing.html', {'form': form})

@login_required
def event_list(request):
    my_events = Event.objects.filter(participants=request.user)
    all_events = Event.objects.all()
    is_admin = request.user.is_staff
    context = {
        'my_events': my_events,
        'all_events': all_events,
        'is_admin': is_admin,  # Add this to your context
    }
    return render(request, 'events/events_list.html', context)

@login_required
def join_event(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    if request.user not in event.participants.all():
        event.participants.add(request.user)
    return redirect('Event:event_list')  

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # Load the profile instance created by the signal
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            auth_login(request, user)
            return redirect('Event:event_list')  # Redirect to a home page or another appropriate page
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def custom_logout_view(request):
    logout(request)
    return redirect('Event:landing')

Events/Event/templates/events/events_list.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'events/list.css' %}" />
{% endblock %}

{% block content %}
<div class="top-bar">
    <span class="brand">events.ie</span>
    <div class="top-bar-options">
      {% if is_admin %}
        <button id="dashboard" class="btn-option">Dashboard</button>
        <button id="addEventButton" class="btn-option">Add Event</button>
      {% endif %}
      <a href="{% url 'Event:logout' %}" class="btn logout-btn">Logout</a>
    </div>
</div>
{% if is_admin %}
<div id="admin-content-placeholder" class="adminContent" style="display: none;">
</div>
<div id="admin-content-placeholder2" class="adminContent2" style="display: none;">
</div>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.getElementById("dashboard").addEventListener("click", function() {
      fetch("{% url 'AdminPage:dashboard' %}")
      .then(response => response.text())
      .then(html => {
          document.getElementById('admin-content-placeholder').style.display = 'none';
          document.getElementById('admin-content-placeholder2').style.display = 'flex';
          document.getElementById('admin-content-placeholder2').innerHTML = html;
      });
    });
  });
</script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
      document.getElementById("addEventButton").addEventListener("click", function() {
          fetch("{% url 'AdminPage:add_event' %}")
          .then(response => response.text())
          .then(html => {
              document.getElementById('admin-content-placeholder').style.display = 'flex';
              document.getElementById('admin-content-placeholder2').style.display = 'none';
              document.getElementById('admin-content-placeholder').innerHTML = html;
          });
      });
  });
</script>
{% else %}
<div class="userContent">
  <div class="list">
    <h2>All Events</h2>
          {% for event in all_events %}
          <li class="all-event-item">
            <span class="element">{{ event.date }}</span>
            <span class="element">{{ event.title }}</span>
            <span class="element">{{ event.location }}</span>
            <a href="{% url 'Event:join_event' event.id %}" class="btn join-btn">Join</a>
          </li>
          {% empty %}
          <p>No events nearby.</p>
        {% endfor %}
  </div>
  <div class="cards">
        {% for event in my_events %}
          <li class="event-item">
            <h3>{{ event.title }}</h3>
            <p><i class="fas fa-map-marker-alt" style="color: black;"></i> {{ event.location }}</p>
            <a href="#" class="btn join-btn">View</a>  
          </li>
        {% empty %}
          <p>No events joined.</p>
        {% endfor %}
  </div>
</div>
{% endif %}
{% endblock %}

Events/Event/templates/events/landing.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}">
<style>
    html, body {
        height: 100%;
        margin: 0;
    }

    body {
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: #3cb371;
    }

    .video-background {
        position: fixed;
        top: 0;
        left: 0;
        min-width: 100%; 
        min-height: 100%;
        width: auto; 
        height: auto;
        z-index: -100;
        background-size: cover;
    }

    .flex-container {
        position: relative;
        z-index: 1;
    }

    .main-container {
        z-index: 1;
    }

    .video-overlay {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.6);
        z-index: 1;
    }   
</style>
{% endblock %}

{% block content %}
<div class="video-background">
    <div class="video-overlay"></div>  <!-- Overlay div -->
    <video autoplay loop muted class="video-background">
        <source src="{% static 'videos/background_video.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
</div>
<div class="flex-container">
    <div class="main-container">
        <div class="banner">
            <h1>Welcome to <span class="gradient-text">events.ie</span></h1>
        </div>
        <div class="login-section">
            <form method="post" action="{% url 'Event:landing' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="button" id="login">Login</button>
                <a href="{% url 'Event:signup' %}" class="button" id="signup">Sign Up</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}