Events/AdminPage/urls.py
from django.urls import path
from . import views

app_name = 'adminpage'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_event/', views.add_event, name='add_event'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('edit_event/<int:event_id>/', views.edit_event, name='edit_event'),
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
]

Events/Event/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'Event'

urlpatterns = [
    path('', views.login_view, name='landing'),
    path('list/', views.event_list, name='event_list'),
    path('join/<int:event_id>/', views.join_event, name='join_event'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.custom_logout_view, name='logout')
]

Events/Events/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminpage/', include(('AdminPage.urls', 'AdminPage'), namespace='AdminPage')),
    path('', include('Event.urls', namespace='Event')),
]

Events/AdminPage/models.py
from django.db import models

# Create your models here.

Events/AdminPage/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from Event.forms import EventForm
from Event.models import Event
from django.contrib.auth.models import User
from django.utils.dateparse import parse_date
from django.contrib import messages
from django.template.loader import render_to_string
from django.http import JsonResponse


def is_admin(user):
    return user.is_authenticated and user.is_superuser

@user_passes_test(is_admin)
def dashboard(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save()
            print(event+'added')
            return redirect('AdminPage:dashboard')
    else:
        form = EventForm()
        events = Event.objects.all()
        users = User.objects.all()  # Fetch users if needed for the dashboard
        return render(request, 'AdminPage/dashboard.html', {'form': form, 'users': users, 'events': events})

@user_passes_test(is_admin)
def add_event(request):
    if request.method == 'POST':
        event_form = EventForm(request.POST)
        if event_form.is_valid():
            event = event_form.save(commit=False)
            date_from = parse_date(request.POST.get('date_from'))
            date_to = parse_date(request.POST.get('date_to'))

            if date_from and date_to:
                event.start_date = date_from
                event.end_date = date_to
                event.save()
                messages.success(request, 'Event created successfully')  
            else:
                messages.error(request, 'There was a problem with the dates.')
            
            return redirect('Event:event_list')
        else:
            for error in event_form.errors:
                messages.error(request, f"{error}: {event_form.errors[error]}")
            return redirect('Event:event_list')
    else:
        event_form = EventForm()
        return render(request, 'AdminPage/addEvent.html', {'form': event_form})

@user_passes_test(is_admin)
def delete_user(request, user_id):
    if request.user.is_staff or request.user.id == user_id:
        try:
            user = get_object_or_404(User, id=user_id)
            user.delete()
            messages.success(request, 'User deleted successfully')
            return redirect('Event:event_list')
        except Exception as e:
            messages.error(request, 'User could not be deleted')
            return redirect('Event:event_list')
    else:
        messages.error(request, 'Unauthorized attempt to delete user')
        return redirect('Event:event_list')
    
@user_passes_test(lambda user: user.is_staff)
def edit_event(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('Event:event_list')
    else:
        form = EventForm(instance=event)
    
    # Render a dedicated edit event template
    return render(request, 'adminpage/editEvent.html', {'form': form, 'event': event})
    
@user_passes_test(is_admin)
def delete_event(request, event_id):
    if request.user.is_staff:
        try:
            event = get_object_or_404(Event, id=event_id)
            event.delete()
            messages.success(request, 'Event deleted successfully')
            return redirect('Event:event_list')
        except:
            messages.error(request, 'Event could not be deleted')
            return redirect('Event:event_list')
    else:
        messages.error(request, 'Unauthorized attempt to delete event')
        return HttpResponse('')

Events/AdminPage/templates/AdminPage/addEvent.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'signup.css' %}">
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock %}

{% block content %}
<script>
function displayPopup(message) {
    Swal.fire({
        icon: 'success',
        title: 'Success!',
        text: message,
        confirmButtonText: 'OK'
    });
}
</script>

{% if messages %}
    {% for message in messages %}
        <script>displayPopup("{{ message }}");</script>
    {% endfor %}
{% endif %}
<div class="editForm">
    <form class="addEvent" method="POST" action="{% url 'adminpage:add_event' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btnSubmit" type="submit">Create Event</button>
    </form>
</div>
{% endblock %}

Events/AdminPage/templates/AdminPage/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'events/list.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
{% endblock %}

{% block content %}
<div class="list">
    <h2>Users</h2>
    <div class="subheads">
        <p class="subheading">Name</p>
        <p class="subheading">Email</p>
        <p class="subheading">Delete</p>
    </div>
    {% for user in users %}
        <div class="user-item">
            <p class="element">{{ user.first_name }}</p>
            <p class="element">{{ user.email }}</p>
            <a href="{% url 'adminpage:delete_user' user.id %}" style="width: 10%;" aria-label="Delete user {{ user.username }}" onclick="return confirm('Are you sure you want to delete this user?');">
                <i class="fas fa-trash" id="delete-user" aria-hidden="true"></i>
            </a>             
        </div>
    {% empty %}
        <p>No users found.</p>
    {% endfor %}
</div>
<div class="cards">
    {% for event in events %}
        <div class="event-item" data-event-id="{{ event.id }}" onclick="openModal(this)">
            <h3>{{ event.title }}</h3>
            <p><i class="fas fa-map-marker-alt" style="color: black;"></i> {{ event.location }}</p>
            <a href="{% url 'adminpage:edit_event' event.id %}" aria-label="Edit event {{ event.title }}" class="edit-event" onclick="event.stopPropagation();">
                <i class="fas fa-edit" id="delete-event"></i>
            </a>
            <a href="{% url 'adminpage:delete_event' event.id %}" style="width: 10%;" aria-label="Delete event {{ event.title }}" onclick="event.stopPropagation(); return confirm('Are you sure you want to delete this event?');">
                <i class="fas fa-trash" id="delete-event" aria-hidden="true"></i>
            </a>
        </div>
    {% empty %}
        <p>No events found.</p>
    {% endfor %}
</div>
{% endblock %}

Events/AdminPage/templates/AdminPage/editEvent.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'signup.css' %}">
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock %}

{% block content %}
<div class="editEvent">
    <div class="editForm">
        <h2>Edit Event</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update Event</button>
    </form>
    </div>
</div>
{% endblock %}